AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 with a security group that enables SSH
Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a8b4cd432b1c3063 # most recent ami id of Amazon Linux2
      InstanceType: t2.micro
      KeyName: Engin_Linux # pem file name without extension
      SecurityGroups:
        - launch-wizard-5 # security group name that allows SSH
      Tags:
        - Key: Name
          Value: Week-2-Project-Stack-Instance
      UserData: 
        Fn::Base64: 
          !Sub | 
            #!/bin/bash 
            yum update -y
            yum install -y httpd
            cd /var/www/html
            wget https://raw.githubusercontent.com/engingltekin/aws-devops-repository/main/AWS/Projects/Deploy-Static-Website-Using-CloudFormation/static-web/index.html
            wget https://github.com/engingltekin/aws-devops-repository/blob/main/AWS/Projects/Deploy-Static-Website-Using-CloudFormation/static-web/cat0.jpg
            wget https://github.com/engingltekin/aws-devops-repository/blob/main/AWS/Projects/Deploy-Static-Website-Using-CloudFormation/static-web/cat1.jpg
            wget https://github.com/engingltekin/aws-devops-repository/blob/main/AWS/Projects/Deploy-Static-Website-Using-CloudFormation/static-web/cat2.jpg
            wget https://github.com/engingltekin/aws-devops-repository/blob/main/AWS/Projects/Deploy-Static-Website-Using-CloudFormation/static-web/cat3.png
            systemctl enable httpd
            systemctl start httpd